#!/usr/bin/env bash
# setup-macos.sh — macOS (Apple Silicon) equivalent of setup.ps1 for the Qwen↔vts pipeline.
# Re-runnable. Ollama uses Metal GPU on Apple Silicon (no NVIDIA / nvidia-smi), and memory is
# UNIFIED, so we pick a model tier by total RAM and let num_gpu 999 push every layer onto Metal.
#
#   bash setup-macos.sh                 # uses ~/.vs-token-safer projectPath as the target repo
#   bash setup-macos.sh /path/to/repo   # pin a target repo
#
# Steps: 1 checks  2 RAM tier  3 vts server deps  4 pull+build model  5 write qvts.config.json  6 verify
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
say() { printf '\033[36m%s\033[0m\n' "$*"; }

# ---- 1. checks ----
command -v node   >/dev/null || { echo "node not found — install Node 18+"; exit 1; }
command -v ollama >/dev/null || { echo "ollama not found — install from https://ollama.com (or: brew install ollama)"; exit 1; }
curl -sf http://127.0.0.1:11434/api/version >/dev/null || { echo "Ollama server not responding on 127.0.0.1:11434 — start the Ollama app or 'ollama serve'"; exit 1; }
say "node $(node --version) · ollama $(ollama --version | head -1)"

# ---- 2. RAM tier (unified memory; leave headroom for macOS + Claude Code) ----
RAM_GB=$(( $(sysctl -n hw.memsize) / 1073741824 ))
if   [ "$RAM_GB" -ge 32 ]; then BASE="qwen2.5-coder:14b-instruct-q4_K_M"; CTX=32768; TIER="14B / 32k";
elif [ "$RAM_GB" -ge 24 ]; then BASE="qwen2.5-coder:14b-instruct-q4_K_M"; CTX=16384; TIER="14B / 16k";
elif [ "$RAM_GB" -ge 16 ]; then BASE="qwen2.5-coder:7b-instruct-q4_K_M";  CTX=16384; TIER="7B / 16k";
else                            BASE="qwen2.5-coder:7b-instruct-q4_K_M";  CTX=8192;  TIER="7B / 8k (tight)"; fi
say "RAM ${RAM_GB} GB  ->  tier: ${TIER}  [${BASE}, num_ctx ${CTX}]"

# ---- 3. vts server deps (dev mode: bridge spawns the cloned server; it needs the MCP SDK + TS LSP) ----
VTS_SERVER="$(cd "$HERE/.." && pwd)/vs-token-safer/server/index.js"
if [ -f "$VTS_SERVER" ]; then
  if [ ! -d "$(dirname "$VTS_SERVER")/node_modules/@modelcontextprotocol" ]; then
    say "installing vs-token-safer server deps (MCP SDK + typescript-language-server + tree-sitter)…"
    ( cd "$(dirname "$VTS_SERVER")" && npm install --no-audit --no-fund --loglevel=error )
  fi
else
  echo "WARNING: vs-token-safer server not found at $VTS_SERVER — clone it next to this repo or set VTS_SERVER."
fi

# ---- 4. pull base + build the tuned variant 'qwen-coder-vts' ----
say "pulling ${BASE} (first run downloads weights)…"
ollama pull "$BASE"
MF="$HERE/Modelfile.generated"
cat > "$MF" <<EOF
# Auto-generated by setup-macos.sh for RAM=${RAM_GB} GB (Apple Silicon / Metal). Re-run setup-macos.sh to refresh.
FROM ${BASE}
PARAMETER num_ctx ${CTX}
PARAMETER num_gpu 999
PARAMETER temperature 0.15
PARAMETER top_p 0.8
PARAMETER top_k 20
PARAMETER repeat_penalty 1.05
PARAMETER num_predict 4096
EOF
ollama create qwen-coder-vts -f "$MF"
say "built model: qwen-coder-vts"

# ---- 5. write qvts.config.json (read by config-loader.mjs for every entry point) ----
PROJECT="${1:-}"
if [ -z "$PROJECT" ] && [ -f "$HOME/.vs-token-safer/config.json" ]; then
  PROJECT="$(node -e "try{process.stdout.write(JSON.parse(require('fs').readFileSync(process.env.HOME+'/.vs-token-safer/config.json','utf8')).projectPath||'')}catch{}")"
fi
node -e "
const fs=require('fs');
const cfg={model:'qwen-coder-vts',numCtx:${CTX},maxSteps:25,
  vtsServer:'${VTS_SERVER}',project:'${PROJECT}'||null,clangd:null,
  port:7878,ollamaHost:'http://127.0.0.1:11434',ramGB:${RAM_GB},tier:'Apple Silicon ${TIER} (macOS Metal)'};
fs.writeFileSync('${HERE}/qvts.config.json',JSON.stringify(cfg,null,2)+'\n');
"
say "wrote qvts.config.json (target: ${PROJECT:-<none — set VTS_PROJECT>})"

# ---- 6. verify ----
ollama run qwen-coder-vts "ok" >/dev/null 2>&1 || true
say ""
printf '\033[32mDONE.\033[0m\n'
ollama ps
echo ""
echo "  CLI:        node vts-bridge.mjs \"where is X declared?\""
echo "  Dashboard:  node dashboard.mjs        (http://127.0.0.1:7878)"
echo "  Verify GPU: ollama ps  -> PROCESSOR must read 100% GPU"
