#!/usr/bin/env bash
# setup-macos.sh — macOS (Apple Silicon) equivalent of setup.ps1 for the Qwen↔vts pipeline.
# Re-runnable. Ollama uses Metal GPU on Apple Silicon (no NVIDIA / nvidia-smi), and memory is
# UNIFIED, so we pick a model tier by total RAM and let num_gpu 999 push every layer onto Metal.
#
#   bash setup-macos.sh                 # uses ~/.vs-token-safer projectPath as the target repo
#   bash setup-macos.sh /path/to/repo   # pin a target repo
#
# Steps: 1 checks  2 RAM tier  3 vts server deps  4 pull+build model  5 write qvts.config.json  6 verify
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
say() { printf '\033[36m%s\033[0m\n' "$*"; }

# ---- 1. checks ----
command -v node   >/dev/null || { echo "node not found — install Node 18+"; exit 1; }
command -v ollama >/dev/null || { echo "ollama not found — install from https://ollama.com (or: brew install ollama)"; exit 1; }
curl -sf http://127.0.0.1:11434/api/version >/dev/null || { echo "Ollama server not responding on 127.0.0.1:11434 — start the Ollama app or 'ollama serve'"; exit 1; }
say "node $(node --version) · ollama $(ollama --version | head -1)"

# ---- 2. pick the model (default = gemma4:e4b, the benchmarked best locator — publicly pullable) ----
# Override with: QVTS_BASE_MODEL=<ollama tag> bash setup-macos.sh
# gemma4:e4b loads ~10 GB; it needs ~16 GB unified memory to stay 100% on GPU. Under 16 GB we fall back to
# qwen2.5-coder 7B (smaller). gemma uses its own sampler (top_p 0.95 / top_k 64); qwen uses 0.8 / 20.
RAM_GB=$(( $(sysctl -n hw.memsize) / 1073741824 ))
CTX=16384
if [ -n "${QVTS_BASE_MODEL:-}" ]; then
  BASE="$QVTS_BASE_MODEL"; VARIANT="custom-vts"; SAMPLER="qwen"; TIER="custom ($BASE)"
elif [ "$RAM_GB" -ge 16 ]; then
  BASE="gemma4:e4b"; VARIANT="gemma4-vts"; SAMPLER="gemma"; TIER="gemma4:e4b (benchmarked best)"
else
  BASE="qwen2.5-coder:7b-instruct-q4_K_M"; VARIANT="qwen-coder-vts"; SAMPLER="qwen"
  [ "$RAM_GB" -lt 12 ] && CTX=8192
  TIER="qwen2.5-coder 7B (gemma4 needs ~16 GB; falling back)"
fi
say "RAM ${RAM_GB} GB  ->  model: ${VARIANT}  [${BASE}, num_ctx ${CTX}]"

# ---- 3. vts server deps (dev mode: bridge spawns the cloned server; it needs the MCP SDK + TS LSP) ----
VTS_SERVER="$(cd "$HERE/.." && pwd)/vs-token-safer/server/index.js"
if [ -f "$VTS_SERVER" ]; then
  if [ ! -d "$(dirname "$VTS_SERVER")/node_modules/@modelcontextprotocol" ]; then
    say "installing vs-token-safer server deps (MCP SDK + typescript-language-server + tree-sitter)…"
    ( cd "$(dirname "$VTS_SERVER")" && npm install --no-audit --no-fund --loglevel=error )
  fi
else
  echo "WARNING: vs-token-safer server not found at $VTS_SERVER — clone it next to this repo or set VTS_SERVER."
fi

# ---- 4. pull base + build the tuned variant ----
say "pulling ${BASE} (first run downloads weights)…"
ollama pull "$BASE"
MF="$HERE/Modelfile.generated"
{
  echo "# Auto-generated by setup-macos.sh for RAM=${RAM_GB} GB (Apple Silicon / Metal). Re-run to refresh."
  echo "FROM ${BASE}"
  echo "PARAMETER num_ctx ${CTX}"
  echo "PARAMETER num_gpu 999"
  echo "PARAMETER temperature 0.15"
  echo "PARAMETER num_predict 4096"
  if [ "$SAMPLER" = "gemma" ]; then
    echo "PARAMETER top_p 0.95"   # Gemma's recommended sampler
    echo "PARAMETER top_k 64"
  else
    echo "PARAMETER top_p 0.8"    # Qwen's recommended sampler
    echo "PARAMETER top_k 20"
    echo "PARAMETER repeat_penalty 1.05"
  fi
} > "$MF"
ollama create "$VARIANT" -f "$MF"
say "built model: ${VARIANT}"

# ---- 5. write qvts.config.json (read by config-loader.mjs for every entry point) ----
PROJECT="${1:-}"
if [ -z "$PROJECT" ] && [ -f "$HOME/.vs-token-safer/config.json" ]; then
  PROJECT="$(node -e "try{process.stdout.write(JSON.parse(require('fs').readFileSync(process.env.HOME+'/.vs-token-safer/config.json','utf8')).projectPath||'')}catch{}")"
fi
VARIANT="$VARIANT" node -e "
const fs=require('fs');
const cfg={model:process.env.VARIANT,numCtx:${CTX},maxSteps:25,
  vtsServer:'${VTS_SERVER}',project:'${PROJECT}'||null,clangd:null,
  port:7878,ollamaHost:'http://127.0.0.1:11434',ramGB:${RAM_GB},tier:'Apple Silicon ${TIER} (macOS Metal)'};
fs.writeFileSync('${HERE}/qvts.config.json',JSON.stringify(cfg,null,2)+'\n');
"
say "wrote qvts.config.json (model: ${VARIANT}, target: ${PROJECT:-<none — set VTS_PROJECT>})"

# ---- 6. verify ----
ollama run "$VARIANT" "ok" >/dev/null 2>&1 || true
say ""
printf '\033[32mDONE.\033[0m\n'
ollama ps
echo ""
echo "  CLI:        node vts-bridge.mjs \"where is X declared?\""
echo "  Dashboard:  node dashboard.mjs        (http://127.0.0.1:7878)"
echo "  Verify GPU: ollama ps  -> PROCESSOR must read 100% GPU"
